### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by ryotaka18** [ryo-techcamp/furima-29181#13]
URL　:　https://furima-29181-1.herokuapp.com/
ID　:　ryo81
パスワード　：　8119
出品者メールアドレス　：　hurleyx.hp.81rt@tokutoku
出品者パスワード　：　ryo08014319
購入者メールアドレス　：　hurleyx.hp.81rt@odaoda
購入者パスワード　：　ryo08014319
購入用カード
番号： 4242424242424242
期限： 12/21
cvc:  123

**Comment by rumaruma0408** [comment]
ryo-techcampさん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
◯ログアウトした状態でも、商品詳細ページを閲覧できる
→以下のエラーが表示されます
https://i.gyazo.com/0d5da2493ac72e0b1d77f4a99d6ab043.png

◯商品出品時に登録した情報が見られるようになっている
→商品説明が表示されておりません

◯商品購入ができませんでした。以下のエラーが表示されます。
https://i.gyazo.com/0ae1ecb937a2e009cb395e7dbf673648.png

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by tec-camp** [comment]
ryo-techcampさん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
◯購入した商品は、再度購入できない状態になっている
→再度購入できてしまう
○売却済みの商品は、「sold out」の文字が表示されるようになっている
→購入してもsold outという表記がされない

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by tec-camp** [comment]
ryo-techcampさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

「修正任意項目」
○ 購入を行う際に必須要件である「都道府県」が無選択でも購入できてしまう
→都道府県が必須項目となっていますが、都道府県を選択しなくても購入できる仕様になっております。就職活動を行う際に、企業の担当者が挙動確認を行う可能性もあります。今回、必須要件ではありませんが必要に応じて修正いただいた方がよいかと存じます。

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
